/** Legal document field keys — aligned with partnersite PROFILE_LEGAL_DOC_CONFIG. */
export const PROFILE_LEGAL_DOC_CONFIG = [
  {
    prefix: "pan",
    label: "PAN",
    numberKey: "pan_document_number",
    holderKey: "pan_holder_name",
    expiryKey: "pan_expiry_date",
    urlKey: "pan_document_url",
    verifiedKey: "pan_is_verified",
  },
  {
    prefix: "gst",
    label: "GST",
    numberKey: "gst_document_number",
    expiryKey: "gst_expiry_date",
    urlKey: "gst_document_url",
    verifiedKey: "gst_is_verified",
  },
  {
    prefix: "aadhaar",
    label: "Aadhaar",
    numberKey: "aadhaar_document_number",
    holderKey: "aadhaar_holder_name",
    expiryKey: "aadhaar_expiry_date",
    urlKey: "aadhaar_document_url",
    verifiedKey: "aadhaar_is_verified",
  },
  {
    prefix: "fssai",
    label: "FSSAI",
    numberKey: "fssai_document_number",
    expiryKey: "fssai_expiry_date",
    urlKey: "fssai_document_url",
    verifiedKey: "fssai_is_verified",
  },
  {
    prefix: "trade_license",
    label: "Trade License",
    numberKey: "trade_license_document_number",
    expiryKey: "trade_license_expiry_date",
    urlKey: "trade_license_document_url",
    verifiedKey: "trade_license_is_verified",
  },
  {
    prefix: "drug_license",
    label: "Drug License",
    numberKey: "drug_license_document_number",
    expiryKey: "drug_license_expiry_date",
    urlKey: "drug_license_document_url",
    verifiedKey: "drug_license_is_verified",
  },
  {
    prefix: "shop_establishment",
    label: "Shop Establishment",
    numberKey: "shop_establishment_document_number",
    expiryKey: "shop_establishment_expiry_date",
    urlKey: "shop_establishment_document_url",
    verifiedKey: "shop_establishment_is_verified",
  },
  {
    prefix: "udyam",
    label: "Udyam",
    numberKey: "udyam_document_number",
    expiryKey: "udyam_expiry_date",
    urlKey: "udyam_document_url",
    verifiedKey: "udyam_is_verified",
  },
  {
    prefix: "other",
    label: "Other Document",
    numberKey: "other_document_number",
    typeKey: "other_document_type",
    expiryKey: "other_expiry_date",
    urlKey: "other_document_url",
    verifiedKey: "other_is_verified",
  },
] as const;
