import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

// POST - Create a new food order
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const {
      userId,
      userName,
      userPhone,
      userEmail,
      restaurantId,
      restaurantName,
      restaurantImage,
      items,
      subtotal,
      deliveryFee,
      taxes,
      discount,
      totalAmount,
      couponCode,
      couponDiscount,
      deliveryAddress,
      deliveryInstructions,
      paymentMethod,
    } = body

    // Validate required fields
    if (!userId || !userName || !userPhone || !restaurantId || !restaurantName || !items || items.length === 0) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Insert the order - order_number will be auto-generated by database trigger (GMF0001 format)
    const { data, error } = await supabase
      .from('food_orders')
      .insert({
        user_id: userId,
        user_name: userName,
        user_phone: userPhone,
        user_email: userEmail || null,
        restaurant_id: restaurantId,
        restaurant_name: restaurantName,
        restaurant_image: restaurantImage || null,
        items: items,
        subtotal: subtotal || 0,
        delivery_fee: deliveryFee || 0,
        taxes: taxes || 0,
        discount: discount || 0,
        total_amount: totalAmount || 0,
        coupon_code: couponCode || null,
        coupon_discount: couponDiscount || 0,
        delivery_address: deliveryAddress || {},
        delivery_instructions: deliveryInstructions || null,
        status: 'pending',
        payment_method: paymentMethod || 'cash',
        payment_status: 'pending',
      })
      .select()
      .single()

    if (error) {
      console.error('Error creating food order:', error)
      return NextResponse.json(
        { error: 'Failed to create order', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      order: data,
      message: 'Order placed successfully'
    })

  } catch (error) {
    console.error('Error in food order API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// GET - Get food orders for a user
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const userId = searchParams.get('userId')
    const orderId = searchParams.get('orderId')
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '20')
    const offset = parseInt(searchParams.get('offset') || '0')

    let query = supabase
      .from('food_orders')
      .select('*')
      .order('created_at', { ascending: false })

    if (userId) {
      query = query.eq('user_id', userId)
    }

    if (orderId) {
      query = query.eq('id', orderId)
    }

    if (status) {
      query = query.eq('status', status)
    }

    query = query.range(offset, offset + limit - 1)

    const { data, error, count } = await query

    if (error) {
      console.error('Error fetching food orders:', error)
      return NextResponse.json(
        { error: 'Failed to fetch orders', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      orders: data || [],
      count: count || 0
    })

  } catch (error) {
    console.error('Error in food order GET API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PATCH - Update food order status
export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json()
    const { orderId, status, rating, review } = body

    if (!orderId) {
      return NextResponse.json(
        { error: 'Order ID is required' },
        { status: 400 }
      )
    }

    const updateData: Record<string, unknown> = {}
    
    if (status) updateData.status = status
    if (rating) updateData.rating = rating
    if (review) updateData.review = review
    
    if (status === 'delivered') {
      updateData.delivered_at = new Date().toISOString()
    }

    const { data, error } = await supabase
      .from('food_orders')
      .update(updateData)
      .eq('id', orderId)
      .select()
      .single()

    if (error) {
      console.error('Error updating food order:', error)
      return NextResponse.json(
        { error: 'Failed to update order', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      order: data,
      message: 'Order updated successfully'
    })

  } catch (error) {
    console.error('Error in food order PATCH API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
