-- ============================================================================
-- UPDATE RIDER ID TO MINIMUM 4 DIGITS
-- Migration: 0040_update_rider_id_minimum_4_digits
-- Database: Supabase PostgreSQL
-- 
-- This migration ensures that all new rider IDs are at least 4 digits (1000+).
-- If existing riders have IDs < 1000, the sequence will be set to start from
-- 1000 for new riders. Existing riders keep their current IDs.
-- ============================================================================

-- ============================================================================
-- STEP 1: GET CURRENT MAX RIDER ID AND SET SEQUENCE
-- ============================================================================

DO $$
DECLARE
  v_max_id INTEGER;
  v_next_id INTEGER;
  v_sequence_name TEXT := 'riders_id_seq';
BEGIN
  -- Get the current maximum rider ID
  SELECT COALESCE(MAX(id), 0) INTO v_max_id
  FROM riders;
  
  -- Calculate next ID: ensure minimum 1000 (4 digits)
  -- If max_id is already >= 1000, use max_id + 1
  -- Otherwise, start from 1000
  IF v_max_id >= 1000 THEN
    v_next_id := v_max_id + 1;
  ELSE
    v_next_id := 1000;
  END IF;
  
  -- For GENERATED ALWAYS AS IDENTITY, we need to use ALTER TABLE ... ALTER COLUMN ... RESTART
  -- This works for both GENERATED ALWAYS and GENERATED BY DEFAULT AS IDENTITY
  BEGIN
    EXECUTE format('ALTER TABLE riders ALTER COLUMN id RESTART WITH %s', v_next_id);
    RAISE NOTICE 'Rider ID identity column updated. Next rider ID will be: %', v_next_id;
  EXCEPTION
    WHEN OTHERS THEN
      -- Fallback: Try to update sequence directly if it exists
      IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = v_sequence_name
          AND n.nspname = 'public'
      ) THEN
        EXECUTE format('ALTER SEQUENCE %I RESTART WITH %s', v_sequence_name, v_next_id);
        RAISE NOTICE 'Rider ID sequence updated via direct sequence alter. Next rider ID will be: %', v_next_id;
      ELSE
        RAISE WARNING 'Could not update rider ID sequence. Error: %. Please manually set the sequence to start from %', SQLERRM, v_next_id;
      END IF;
  END;
  
  -- Log the current state
  RAISE NOTICE 'Current max rider ID: %, Next rider ID: %', v_max_id, v_next_id;
END $$;

-- ============================================================================
-- STEP 2: VERIFY SEQUENCE SETTING
-- ============================================================================

-- Create a function to get the next rider ID (for verification)
CREATE OR REPLACE FUNCTION get_next_rider_id()
RETURNS INTEGER AS $$
DECLARE
  v_next_id INTEGER;
BEGIN
  -- Try to get next value from sequence
  BEGIN
    SELECT nextval('riders_id_seq') INTO v_next_id;
    -- Rollback the sequence increment by setting it back
    PERFORM setval('riders_id_seq', v_next_id - 1);
    RETURN v_next_id;
  EXCEPTION
    WHEN OTHERS THEN
      -- If sequence doesn't exist, return NULL
      RETURN NULL;
  END;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- STEP 3: ADD CONSTRAINT TO ENSURE MINIMUM 4 DIGITS (ONLY IF NO EXISTING DATA < 1000)
-- ============================================================================

-- Add a check constraint to prevent IDs < 1000 (only if no existing data violates it)
-- Using OID lookup for safer constraint detection and format() for safe identifier quoting
DO $$
DECLARE
  v_riders_below_1000 INTEGER;
  v_con_oid oid;
BEGIN
  -- Check if there are any riders with ID < 1000
  SELECT COUNT(*) INTO v_riders_below_1000
  FROM public.riders
  WHERE id < 1000;

  -- Look up constraint OID by name (more reliable than EXISTS check)
  SELECT c.oid
  INTO v_con_oid
  FROM pg_constraint c
  JOIN pg_class t ON c.conrelid = t.oid
  JOIN pg_namespace n ON t.relnamespace = n.oid
  WHERE c.conname = 'riders_id_minimum_4_digits_check'
    AND t.relname = 'riders'
    AND n.nspname = 'public'
  LIMIT 1;

  -- Drop existing constraint only if OID was found
  IF v_con_oid IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.riders DROP CONSTRAINT %I', 'riders_id_minimum_4_digits_check');
    RAISE NOTICE 'Dropped constraint riders_id_minimum_4_digits_check';
  ELSE
    RAISE NOTICE 'Constraint riders_id_minimum_4_digits_check not found; skipping drop.';
  END IF;

  -- Only add constraint if no existing riders have IDs < 1000
  IF v_riders_below_1000 = 0 THEN
    BEGIN
      ALTER TABLE public.riders
        ADD CONSTRAINT riders_id_minimum_4_digits_check 
        CHECK (id >= 1000);
      RAISE NOTICE 'Added constraint riders_id_minimum_4_digits_check';
    EXCEPTION
      WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint already exists, skipping add.';
      WHEN OTHERS THEN
        RAISE WARNING 'Could not add constraint: %', SQLERRM;
    END;
  ELSE
    RAISE NOTICE 'Skipping adding check constraint — % existing riders with id < 1000', v_riders_below_1000;
  END IF;
END $$;

-- ============================================================================
-- STEP 4: CREATE TRIGGER TO ENFORCE MINIMUM 4 DIGITS ON INSERT
-- ============================================================================

-- Function to ensure new rider IDs are at least 4 digits
-- Note: This is a safeguard. The main enforcement is via sequence setting.
-- With GENERATED ALWAYS AS IDENTITY, the ID is generated before this trigger,
-- so this mainly serves as a validation check.
CREATE OR REPLACE FUNCTION enforce_rider_id_minimum_4_digits()
RETURNS TRIGGER AS $$
BEGIN
  -- If somehow an ID < 1000 is being inserted, raise an error
  -- This should not happen if sequence is properly configured
  IF NEW.id < 1000 THEN
    RAISE EXCEPTION 'Rider ID must be at least 4 digits (>= 1000). Received: %. Please check the riders_id_seq sequence configuration.', NEW.id;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger if exists
DROP TRIGGER IF EXISTS riders_enforce_minimum_4_digits_trigger ON riders;

-- Create trigger (only fires on INSERT, before the row is inserted)
-- Note: With GENERATED ALWAYS AS IDENTITY, the ID is already generated,
-- so this trigger validates rather than modifies
CREATE TRIGGER riders_enforce_minimum_4_digits_trigger
  BEFORE INSERT ON riders
  FOR EACH ROW
  EXECUTE FUNCTION enforce_rider_id_minimum_4_digits();

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON FUNCTION get_next_rider_id() IS 'Returns the next rider ID that will be assigned (for verification purposes)';
COMMENT ON FUNCTION enforce_rider_id_minimum_4_digits() IS 'Ensures new rider IDs are at least 4 digits (>= 1000). This is a safeguard in case sequence is manually modified.';

-- Add comment on constraint only if it exists
DO $$
DECLARE
  v_con_oid oid;
BEGIN
  -- Check if constraint exists
  SELECT c.oid
  INTO v_con_oid
  FROM pg_constraint c
  JOIN pg_class t ON c.conrelid = t.oid
  JOIN pg_namespace n ON t.relnamespace = n.oid
  WHERE c.conname = 'riders_id_minimum_4_digits_check'
    AND t.relname = 'riders'
    AND n.nspname = 'public'
  LIMIT 1;

  -- Only add comment if constraint exists
  IF v_con_oid IS NOT NULL THEN
    EXECUTE format('COMMENT ON CONSTRAINT %I ON public.riders IS %L', 
      'riders_id_minimum_4_digits_check',
      'Ensures rider IDs are minimum 4 digits (>= 1000). Only enforced if no existing riders have IDs < 1000.');
  END IF;
END $$;

-- ============================================================================
-- VERIFICATION QUERY (for manual checking)
-- ============================================================================

-- Uncomment to verify:
-- SELECT 
--   (SELECT COALESCE(MAX(id), 0) FROM riders) AS current_max_id,
--   get_next_rider_id() AS next_rider_id,
--   (SELECT COUNT(*) FROM riders WHERE id < 1000) AS riders_below_1000;
