-- 0463: Ride Settlement Engine v1
--
-- Introduces three foundational objects for the Ride Billing Architecture:
--
--   * ride_settlements         — immutable per-ride settlement snapshot (Hybrid
--                                Residual Take-Rate). One row per ride.
--   * ride_settlement_ledger   — append-only ledger lines (double-entry style,
--                                one credit + one debit per posting) mirroring
--                                every monetary movement generated by settlement.
--   * ride_wallet_config       — Super Admin configurable negative-wallet
--                                thresholds. Backwards-compatible defaults keep
--                                today's behaviour (per-service -50, global -200).
--
-- Extends orders_ride with:
--   * cash_collected_at            — when the rider marked cash-in-hand
--   * cash_collected_by_rider_id   — rider who confirmed cash collection
--   * settlement_id                — pointer to the immutable ride_settlements row
--
-- Idempotent — safe to re-run.

CREATE TABLE IF NOT EXISTS ride_settlements (
  id                    bigserial PRIMARY KEY,
  settlement_id         text        NOT NULL UNIQUE,
  order_core_id         bigint      NOT NULL REFERENCES orders_core(id) ON DELETE CASCADE,
  order_id_text         text        NOT NULL,
  rider_id              integer,
  customer_id           bigint      REFERENCES customers(id) ON DELETE SET NULL,

  payment_mode          text        NOT NULL CHECK (
    payment_mode IN ('online', 'cash', 'wallet', 'mixed')
  ),

  -- Totals
  customer_bill         numeric(14, 2) NOT NULL DEFAULT 0,
  customer_paid         numeric(14, 2) NOT NULL DEFAULT 0,
  company_receivable    numeric(14, 2) NOT NULL DEFAULT 0,
  company_received      numeric(14, 2) NOT NULL DEFAULT 0,
  rider_earnings        numeric(14, 2) NOT NULL DEFAULT 0,
  wallet_debit          numeric(14, 2) NOT NULL DEFAULT 0,
  wallet_credit         numeric(14, 2) NOT NULL DEFAULT 0,
  outstanding_amount    numeric(14, 2) NOT NULL DEFAULT 0,

  -- Bill component snapshot (auditable forever)
  base_fare             numeric(14, 2) NOT NULL DEFAULT 0,
  distance_fare         numeric(14, 2) NOT NULL DEFAULT 0,
  waiting_charge        numeric(14, 2) NOT NULL DEFAULT 0,
  toll_charge           numeric(14, 2) NOT NULL DEFAULT 0,
  night_charge          numeric(14, 2) NOT NULL DEFAULT 0,
  peak_hour_charge      numeric(14, 2) NOT NULL DEFAULT 0,
  festival_charge       numeric(14, 2) NOT NULL DEFAULT 0,
  airport_charge        numeric(14, 2) NOT NULL DEFAULT 0,
  extra_stops_charge    numeric(14, 2) NOT NULL DEFAULT 0,

  platform_fee          numeric(14, 2) NOT NULL DEFAULT 0,
  convenience_fee       numeric(14, 2) NOT NULL DEFAULT 0,
  service_charge        numeric(14, 2) NOT NULL DEFAULT 0,
  gateway_fee           numeric(14, 2) NOT NULL DEFAULT 0,
  small_order_fee       numeric(14, 2) NOT NULL DEFAULT 0,

  surge_total           numeric(14, 2) NOT NULL DEFAULT 0,
  surge_customer_share  numeric(14, 2) NOT NULL DEFAULT 0,
  surge_company_share   numeric(14, 2) NOT NULL DEFAULT 0,

  tax_total             numeric(14, 2) NOT NULL DEFAULT 0,
  discount_total        numeric(14, 2) NOT NULL DEFAULT 0,
  coupon_discount       numeric(14, 2) NOT NULL DEFAULT 0,
  company_funded_discount numeric(14, 2) NOT NULL DEFAULT 0,

  commissionable_base   numeric(14, 2) NOT NULL DEFAULT 0,
  company_commission    numeric(14, 2) NOT NULL DEFAULT 0,
  platform_percentage   numeric(6, 3)  NOT NULL DEFAULT 0,
  rider_percentage      numeric(6, 3)  NOT NULL DEFAULT 0,
  payout_rule_id        integer,

  -- GatiCash / Razorpay split (online mode)
  gati_cash_applied     numeric(14, 2) NOT NULL DEFAULT 0,
  razorpay_amount       numeric(14, 2) NOT NULL DEFAULT 0,
  razorpay_order_id     text,
  razorpay_payment_id   text,

  status                text        NOT NULL DEFAULT 'settled' CHECK (
    status IN ('pending', 'settled', 'failed', 'reversed')
  ),
  status_reason         text,

  -- Audit / lineage
  billing_snapshot_id   bigint      REFERENCES ride_customer_payment_snapshots(id) ON DELETE SET NULL,
  billing_snapshot      jsonb       NOT NULL DEFAULT '{}'::jsonb,
  component_breakdown   jsonb       NOT NULL DEFAULT '{}'::jsonb,
  metadata              jsonb       NOT NULL DEFAULT '{}'::jsonb,

  posted_at             timestamptz NOT NULL DEFAULT NOW(),
  created_at            timestamptz NOT NULL DEFAULT NOW(),
  updated_at            timestamptz NOT NULL DEFAULT NOW()
);

-- Attach rider FK if riders table exists (all live envs do). Kept idempotent
-- so re-running the migration on a fresh DB where riders was created earlier
-- in the same migration set does not fail.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'riders' AND relkind = 'r')
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'ride_settlements_rider_id_fkey'
     ) THEN
    ALTER TABLE ride_settlements
      ADD CONSTRAINT ride_settlements_rider_id_fkey
      FOREIGN KEY (rider_id) REFERENCES riders(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ride_settlements_order_core_uidx
  ON ride_settlements(order_core_id);

CREATE INDEX IF NOT EXISTS ride_settlements_rider_idx
  ON ride_settlements(rider_id, posted_at DESC);

CREATE INDEX IF NOT EXISTS ride_settlements_customer_idx
  ON ride_settlements(customer_id, posted_at DESC)
  WHERE customer_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ride_settlements_payment_mode_idx
  ON ride_settlements(payment_mode, posted_at DESC);

CREATE INDEX IF NOT EXISTS ride_settlements_status_idx
  ON ride_settlements(status, posted_at DESC);

COMMENT ON TABLE ride_settlements IS
  'Immutable per-ride settlement snapshot (Hybrid Residual Take-Rate). Written inside the wallet transaction; one row per ride.';

-- ---------------------------------------------------------------------------
-- ride_settlement_ledger — append-only ledger. Each posting emits paired lines
-- (one debit + one credit) so totals always balance to zero.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ride_settlement_ledger (
  id                bigserial PRIMARY KEY,
  settlement_id     text        NOT NULL REFERENCES ride_settlements(settlement_id) ON DELETE CASCADE,
  order_core_id     bigint      NOT NULL,
  rider_id          integer,
  customer_id       bigint,

  direction         text        NOT NULL CHECK (direction IN ('debit', 'credit')),
  amount            numeric(14, 2) NOT NULL,
  account_kind      text        NOT NULL CHECK (
    account_kind IN (
      'rider_wallet',
      'customer_cash',
      'gateway_online',
      'gati_cash',
      'company_receivable',
      'company_revenue',
      'company_commission',
      'company_tax',
      'company_platform_fee',
      'company_convenience_fee',
      'company_service_charge',
      'company_gateway_fee',
      'company_surge_share',
      'company_discount_subsidy',
      'rider_earning_kept',
      'rider_earning_credited'
    )
  ),
  reason_code       text        NOT NULL CHECK (
    reason_code IN (
      'RIDE_EARNING_CREDIT',
      'RIDE_EARNING_KEPT_IN_CASH',
      'CASH_COMPANY_RECOVERY',
      'COMMISSION',
      'TAX',
      'PLATFORM_FEE',
      'CONVENIENCE_FEE',
      'SERVICE_CHARGE',
      'GATEWAY_FEE',
      'SURGE_CUSTOMER',
      'SURGE_COMPANY',
      'DISCOUNT',
      'CUSTOMER_ONLINE_PAY',
      'CUSTOMER_GATI_CASH_PAY',
      'CUSTOMER_CASH_PAY',
      'REFUND',
      'ADJUSTMENT'
    )
  ),
  description       text,
  metadata          jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ride_settlement_ledger_settlement_idx
  ON ride_settlement_ledger(settlement_id, created_at);

CREATE INDEX IF NOT EXISTS ride_settlement_ledger_order_idx
  ON ride_settlement_ledger(order_core_id, created_at);

CREATE INDEX IF NOT EXISTS ride_settlement_ledger_rider_idx
  ON ride_settlement_ledger(rider_id, created_at DESC)
  WHERE rider_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ride_settlement_ledger_reason_idx
  ON ride_settlement_ledger(reason_code, created_at DESC);

COMMENT ON TABLE ride_settlement_ledger IS
  'Append-only ride settlement postings (paired debit + credit). Never overwritten. Feeds admin financial reports and reconciliation.';

-- ---------------------------------------------------------------------------
-- ride_wallet_config — Super Admin controlled negative-wallet policy. Defaults
-- match today's hardcoded constants so behaviour is unchanged until the admin
-- overrides them.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ride_wallet_config (
  id                          bigserial PRIMARY KEY,
  service_negative_threshold  numeric(10, 2) NOT NULL DEFAULT 50,
  global_block_threshold      numeric(10, 2) NOT NULL DEFAULT -200,
  cash_settlement_enabled     boolean        NOT NULL DEFAULT TRUE,
  auto_unblock_on_zero        boolean        NOT NULL DEFAULT TRUE,
  is_active                   boolean        NOT NULL DEFAULT TRUE,
  updated_by_system_user_id   integer,
  notes                       text,
  created_at                  timestamptz    NOT NULL DEFAULT NOW(),
  updated_at                  timestamptz    NOT NULL DEFAULT NOW()
);

-- Only one active policy row at a time.
CREATE UNIQUE INDEX IF NOT EXISTS ride_wallet_config_active_uidx
  ON ride_wallet_config(is_active)
  WHERE is_active = TRUE;

INSERT INTO ride_wallet_config (
  service_negative_threshold, global_block_threshold,
  cash_settlement_enabled, auto_unblock_on_zero, is_active, notes
)
SELECT 50, -200, TRUE, TRUE, TRUE,
       '0463: default Ride Wallet policy (per-service -50 / global -200)'
WHERE NOT EXISTS (
  SELECT 1 FROM ride_wallet_config WHERE is_active = TRUE
);

COMMENT ON TABLE ride_wallet_config IS
  'Super Admin controlled Ride Wallet policy. Only one row is_active at a time; edits create a new active row after deactivating the old one (audit trail via ride_wallet_config_history).';

CREATE TABLE IF NOT EXISTS ride_wallet_config_history (
  id                          bigserial PRIMARY KEY,
  service_negative_threshold  numeric(10, 2) NOT NULL,
  global_block_threshold      numeric(10, 2) NOT NULL,
  cash_settlement_enabled     boolean        NOT NULL,
  auto_unblock_on_zero        boolean        NOT NULL,
  changed_by_system_user_id   integer,
  reason                      text,
  effective_from              timestamptz    NOT NULL DEFAULT NOW(),
  metadata                    jsonb          NOT NULL DEFAULT '{}'::jsonb,
  created_at                  timestamptz    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ride_wallet_config_history_effective_idx
  ON ride_wallet_config_history(effective_from DESC);

COMMENT ON TABLE ride_wallet_config_history IS
  'Immutable history of Ride Wallet policy changes. Written every time ride_wallet_config changes.';

-- ---------------------------------------------------------------------------
-- orders_ride extensions for cash + settlement lineage
-- ---------------------------------------------------------------------------

ALTER TABLE orders_ride
  ADD COLUMN IF NOT EXISTS cash_collected_at timestamptz;

ALTER TABLE orders_ride
  ADD COLUMN IF NOT EXISTS cash_collected_by_rider_id integer;

ALTER TABLE orders_ride
  ADD COLUMN IF NOT EXISTS settlement_id text;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'orders_ride_cash_collected_by_rider_fkey'
  ) AND EXISTS (SELECT 1 FROM pg_class WHERE relname = 'riders' AND relkind = 'r') THEN
    ALTER TABLE orders_ride
      ADD CONSTRAINT orders_ride_cash_collected_by_rider_fkey
      FOREIGN KEY (cash_collected_by_rider_id)
      REFERENCES riders(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS orders_ride_cash_collected_idx
  ON orders_ride(cash_collected_at DESC)
  WHERE cash_collected_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS orders_ride_settlement_idx
  ON orders_ride(settlement_id)
  WHERE settlement_id IS NOT NULL;
