-- Rollback for 0518_notification_lifecycle_templates.sql
DELETE FROM public.notification_templates
WHERE code IN (
  'CUSTOMER_ADDRESS_UPDATED',
  'CUSTOMER_SUPPORT_TICKET',
  'RIDER_SUPPORT_TICKET',
  'MERCHANT_STORE_SUSPENDED',
  'MERCHANT_STORE_APPROVED',
  'MERCHANT_MENU_APPROVED',
  'MERCHANT_MENU_REJECTED',
  'RIDER_SHIFT_REMINDER',
  'RIDER_ATTENDANCE',
  'RIDER_INCENTIVE',
  'CUSTOMER_INACTIVE_REMINDER',
  'CUSTOMER_KYC_REMINDER',
  'CUSTOMER_WALLET_REMINDER',
  'MERCHANT_SUBSCRIPTION_REMINDER',
  'RIDER_ORDER_REASSIGNED',
  'RIDER_PICKUP_REMINDER',
  'RIDER_DELIVERY_REMINDER'
) AND locale = 'en';
