-- 0545: Persistent per-store onboarding tasks (source of truth for Home card).
-- I/O: one CREATE + unique index; one-pass backfill from settings_metadata JSON.
-- Completion is immutable: expiry never resets COMPLETED → INCOMPLETE.

CREATE TABLE IF NOT EXISTS public.merchant_onboarding_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES public.merchant_stores(id) ON DELETE CASCADE,
  task_key text NOT NULL,
  status text NOT NULL DEFAULT 'INCOMPLETE',
  completed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_by text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT merchant_onboarding_tasks_status_chk
    CHECK (status IN ('INCOMPLETE', 'COMPLETED')),
  CONSTRAINT merchant_onboarding_tasks_completed_chk
    CHECK (status <> 'COMPLETED' OR completed_at IS NOT NULL),
  CONSTRAINT merchant_onboarding_tasks_store_task_uk UNIQUE (store_id, task_key)
);

CREATE INDEX IF NOT EXISTS merchant_onboarding_tasks_store_id_idx
  ON public.merchant_onboarding_tasks (store_id);

CREATE INDEX IF NOT EXISTS merchant_onboarding_tasks_status_idx
  ON public.merchant_onboarding_tasks (store_id, status);

-- Never let expiry or a client PATCH roll a completed task back to pending.
CREATE OR REPLACE FUNCTION public.merchant_onboarding_tasks_protect_completion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'COMPLETED' THEN
    NEW.status := 'COMPLETED';
    NEW.completed_at := COALESCE(OLD.completed_at, NEW.completed_at, now());
    NEW.completed_by := COALESCE(OLD.completed_by, NEW.completed_by);
    IF OLD.expires_at IS NOT NULL THEN
      NEW.expires_at := OLD.expires_at;
    END IF;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS merchant_onboarding_tasks_protect_completion_trg
  ON public.merchant_onboarding_tasks;
CREATE TRIGGER merchant_onboarding_tasks_protect_completion_trg
  BEFORE UPDATE ON public.merchant_onboarding_tasks
  FOR EACH ROW
  EXECUTE FUNCTION public.merchant_onboarding_tasks_protect_completion();

-- Backfill from existing settings_metadata.onboarding_benefits (no invented completions).
INSERT INTO public.merchant_onboarding_tasks (
  store_id,
  task_key,
  status,
  completed_at,
  expires_at,
  created_at,
  updated_at,
  metadata
)
SELECT
  s.store_id,
  'ONBOARDING_BENEFITS',
  CASE
    WHEN NULLIF(btrim(ob->>'completed_at'), '') IS NOT NULL THEN 'COMPLETED'
    ELSE 'INCOMPLETE'
  END,
  CASE
    WHEN NULLIF(btrim(ob->>'completed_at'), '') IS NOT NULL
      THEN (ob->>'completed_at')::timestamptz
    ELSE NULL
  END,
  CASE
    WHEN NULLIF(btrim(ob->>'started_at'), '') IS NOT NULL
      THEN (ob->>'started_at')::timestamptz + INTERVAL '15 days'
    WHEN NULLIF(btrim(ob->>'completed_at'), '') IS NOT NULL
      THEN (ob->>'completed_at')::timestamptz + INTERVAL '15 days'
    ELSE NULL
  END,
  COALESCE(
    NULLIF(btrim(ob->>'started_at'), '')::timestamptz,
    NULLIF(btrim(ob->>'completed_at'), '')::timestamptz,
    s.updated_at,
    now()
  ),
  now(),
  jsonb_strip_nulls(
    jsonb_build_object(
      'started_at', NULLIF(btrim(ob->>'started_at'), ''),
      'packaging_tips_completed_at', NULLIF(btrim(ob->>'packaging_tips_completed_at'), ''),
      'dismissed_at', NULLIF(btrim(ob->>'dismissed_at'), ''),
      'legacy_source', 'settings_metadata.onboarding_benefits'
    )
  )
FROM public.merchant_store_settings s
CROSS JOIN LATERAL (
  SELECT COALESCE(s.settings_metadata->'onboarding_benefits', '{}'::jsonb) AS ob
) x
WHERE s.store_id IS NOT NULL
  AND s.settings_metadata ? 'onboarding_benefits'
  AND (
    NULLIF(btrim(ob->>'completed_at'), '') IS NOT NULL
    OR NULLIF(btrim(ob->>'started_at'), '') IS NOT NULL
  )
  AND (
    NULLIF(btrim(ob->>'completed_at'), '') IS NULL
    OR btrim(ob->>'completed_at') ~ '^[0-9]{4}-'
  )
  AND (
    NULLIF(btrim(ob->>'started_at'), '') IS NULL
    OR btrim(ob->>'started_at') ~ '^[0-9]{4}-'
  )
ON CONFLICT (store_id, task_key) DO NOTHING;
