/**
 * Auto-generated offer names like "Flat 10% Off" must follow the live discount %.
 * Custom merchant titles (e.g. "Summer Pizza Deal") are left alone.
 */

const GENERATED_PCT =
  /^(?:flat\s+)?(\d+(?:\.\d+)?)%\s+off(?:\s+up to\s+₹?\s*[\d,]+)?$/i;
const GENERATED_FLAT_RUPEE = /^flat\s+₹?\s*[\d,]+\s+off$/i;
const GENERATED_BOGO = /^buy\s+\d+\s+get\s+\d+\s+free$/i;

export function isAutoGeneratedOfferTitle(title: string | null | undefined): boolean {
  const t = String(title ?? "").trim();
  if (!t) return true;
  return GENERATED_PCT.test(t) || GENERATED_FLAT_RUPEE.test(t) || GENERATED_BOGO.test(t);
}

export function canonicalPercentageOfferTitle(
  pct: number,
  cap?: number | null
): string {
  if (cap != null && Number.isFinite(Number(cap)) && Number(cap) > 0) {
    return `${pct}% Off up to ₹${cap}`;
  }
  return `Flat ${pct}% Off`;
}

export function nextOfferTitleAfterDiscountChange(
  prevTitle: string | null | undefined,
  pct: number,
  cap?: number | null
): string {
  if (!isAutoGeneratedOfferTitle(prevTitle)) return String(prevTitle ?? "").trim();
  return canonicalPercentageOfferTitle(pct, cap);
}

export function syncedGeneratedOfferTitle(offer: {
  offer_title?: string | null;
  offer_type?: string | null;
  discount_percentage?: unknown;
  discount_value?: unknown;
  max_discount_amount?: unknown;
  buy_quantity?: unknown;
  get_quantity?: unknown;
}): string {
  const title = String(offer.offer_title ?? "").trim();
  if (!isAutoGeneratedOfferTitle(title)) return title;
  const type = String(offer.offer_type ?? "").toUpperCase();
  if (type === "PERCENTAGE" || type === "COUPON" || type === "CART_PERCENTAGE") {
    const pct = Number(offer.discount_percentage ?? offer.discount_value);
    if (Number.isFinite(pct) && pct > 0) {
      const capRaw = Number(offer.max_discount_amount);
      const cap = Number.isFinite(capRaw) && capRaw > 0 ? capRaw : null;
      return canonicalPercentageOfferTitle(pct, cap);
    }
  }
  if (type === "FLAT" || type === "CART_FLAT") {
    const amt = Number(offer.discount_value);
    if (Number.isFinite(amt) && amt > 0) return `Flat ₹${amt} Off`;
  }
  if (type === "BOGO" || type === "BUY_X_GET_Y" || type === "BUY_N_GET_M") {
    const buy = Math.max(1, Number(offer.buy_quantity) || 1);
    const get = Math.max(1, Number(offer.get_quantity) || 1);
    return `Buy ${buy} Get ${get} Free`;
  }
  return title;
}
