export const STANDARD_REMARKS: Record<"CUSTOMER" | "MERCHANT" | "RIDER" | "OTHER", string[]> = {
  CUSTOMER: [
    "Customer confirmed the delivery.",
    "Customer has not received the order yet.",
    "Not able to connect with customer.",
    "Customer will pick up the order later.",
    "Manual adjustment form filled.",
    "Issue raised in internal group.",
    "Customer is not answering the call.",
    "Customer requested rider to come to another location.",
    "Wrong drop location provided by customer.",
    "Delivery will be marked after customer confirmation.",
    "Delivery charge refund to be processed after confirmation.",
  ],
  MERCHANT: [
    "Not able to connect.",
    "Not able to connect, raised in WhatsApp group.",
    "Mx asked for callback later to provide update.",
    "Issue raised in internal group.",
    "Mx is preparing the order. Will handover parcel to rider shortly.",
    "Mx has handed over the parcel to the rider.",
    "Merchant not available at store.",
    "Store closed.",
    "Store timing changed.",
    "Store closed — order cancelled and refunded.",
    "Merchant denied due to commission/menu/payment issue.",
    "Mx denied to handover the order.",
    "Mx confirmed order was not delivered — refunded to user.",
    "Wrong order issue - Raised to the store partner.",
    "Expired item issue — raised to store partner.",
    "Refund deducted from Mx wallet.",
    "IOOS — cancelled.",
    "Order cancelled and refunded.",
  ],
  RIDER: [
    "Rider unresponsive — raised to 3PL.",
    "Merchant will deliver order on behalf of platform.",
    "Manually assigned rider.",
    "Customer will pick up the order later.",
    "Rider is on the way to merchant, will reach shortly.",
    "Ride cancelled and new rider assigned — raised to 3PL.",
    "Rider denied pickup — raised to 3PL.",
    "Rider app issue, unable to view order — raised to 3PL.",
    "Rider reached merchant and waiting for order.",
    "Location issue — unable to find store.",
    "Rider waiting at store, merchant preparing order.",
    "Unable to connect with rider — raised to 3PL.",
    "Rider denied to wait due to merchant delay — raised to 3PL.",
    "Rider on the way to drop point, will deliver shortly.",
    "Rider reached drop location and confirming with customer.",
    "Delivery may exceed ETA.",
    "Met with accident — order cancelled.",
    "Issue raised in internal group.",
  ],
  OTHER: [
    "Duplicate Order",
    "Wrong order",
    "Missing Item",
    "Customer reject due to delay",
    "PG failure",
    "Out of subzone/area",
    "unsafe area",
    "Product Outside deals-in",
    "Customer ordering in bulk",
    "Invalid prescription",
    "Prescription missing",
    "Issue with pricing",
  ],
};

