import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

// POST - Create a new ride booking (person order)
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const {
      userId,
      userName,
      userPhone,
      userEmail,
      vehicleType,
      vehicleName,
      pickupLocation,
      dropoffLocation,
      distanceKm,
      baseFare,
      distanceFare,
      timeFare,
      surgeMultiplier,
      taxes,
      discount,
      totalAmount,
      couponCode,
      couponDiscount,
      isScheduled,
      scheduledTime,
      paymentMethod,
      estimatedArrivalTime,
      estimatedRideDuration,
    } = body

    // Validate required fields
    if (!userId || !userName || !userPhone || !vehicleType || !vehicleName || !pickupLocation || !dropoffLocation) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Insert the booking - booking_number will be auto-generated by database trigger (GMP0001 format)
    const { data, error } = await supabase
      .from('person_orders')
      .insert({
        user_id: userId,
        user_name: userName,
        user_phone: userPhone,
        user_email: userEmail || null,
        vehicle_type: vehicleType,
        vehicle_name: vehicleName,
        pickup_location: pickupLocation,
        dropoff_location: dropoffLocation,
        distance_km: distanceKm || null,
        base_fare: baseFare || 0,
        distance_fare: distanceFare || 0,
        time_fare: timeFare || 0,
        surge_multiplier: surgeMultiplier || 1.0,
        taxes: taxes || 0,
        discount: discount || 0,
        total_amount: totalAmount || 0,
        coupon_code: couponCode || null,
        coupon_discount: couponDiscount || 0,
        is_scheduled: isScheduled || false,
        scheduled_time: scheduledTime || null,
        status: 'pending',
        payment_method: paymentMethod || 'cash',
        payment_status: 'pending',
        estimated_arrival_time: estimatedArrivalTime || null,
        estimated_ride_duration: estimatedRideDuration || null,
      })
      .select()
      .single()

    if (error) {
      console.error('Error creating ride booking:', error)
      return NextResponse.json(
        { error: 'Failed to create booking', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      booking: data,
      message: 'Ride booked successfully'
    })

  } catch (error) {
    console.error('Error in ride booking API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// GET - Get ride bookings for a user
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const userId = searchParams.get('userId')
    const bookingId = searchParams.get('bookingId')
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '20')
    const offset = parseInt(searchParams.get('offset') || '0')

    let query = supabase
      .from('person_orders')
      .select('*')
      .order('created_at', { ascending: false })

    if (userId) {
      query = query.eq('user_id', userId)
    }

    if (bookingId) {
      query = query.eq('id', bookingId)
    }

    if (status) {
      query = query.eq('status', status)
    }

    query = query.range(offset, offset + limit - 1)

    const { data, error, count } = await query

    if (error) {
      console.error('Error fetching ride bookings:', error)
      return NextResponse.json(
        { error: 'Failed to fetch bookings', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      bookings: data || [],
      count: count || 0
    })

  } catch (error) {
    console.error('Error in ride booking GET API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PATCH - Update ride booking status
export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json()
    const { bookingId, status, driverId, driverName, driverPhone, driverPhoto, vehicleNumber, driverRating, rating, review } = body

    if (!bookingId) {
      return NextResponse.json(
        { error: 'Booking ID is required' },
        { status: 400 }
      )
    }

    const updateData: Record<string, unknown> = {}
    
    if (status) updateData.status = status
    if (driverId) updateData.driver_id = driverId
    if (driverName) updateData.driver_name = driverName
    if (driverPhone) updateData.driver_phone = driverPhone
    if (driverPhoto) updateData.driver_photo = driverPhoto
    if (vehicleNumber) updateData.vehicle_number = vehicleNumber
    if (driverRating) updateData.driver_rating = driverRating
    if (rating) updateData.rating = rating
    if (review) updateData.review = review
    
    // Auto-set timestamps based on status
    if (status === 'driver_assigned') {
      updateData.driver_assigned_at = new Date().toISOString()
    } else if (status === 'in_transit') {
      updateData.ride_started_at = new Date().toISOString()
    } else if (status === 'completed') {
      updateData.ride_completed_at = new Date().toISOString()
    }

    const { data, error } = await supabase
      .from('person_orders')
      .update(updateData)
      .eq('id', bookingId)
      .select()
      .single()

    if (error) {
      console.error('Error updating ride booking:', error)
      return NextResponse.json(
        { error: 'Failed to update booking', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      booking: data,
      message: 'Booking updated successfully'
    })

  } catch (error) {
    console.error('Error in ride booking PATCH API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
