import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

// POST - Create a new parcel order
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const {
      senderId,
      senderName,
      senderPhone,
      senderEmail,
      recipientName,
      recipientPhone,
      recipientEmail,
      parcelType,
      parcelTypeName,
      parcelWeight,
      parcelDescription,
      pickupAddress,
      deliveryAddress,
      distanceKm,
      deliveryType,
      basePrice,
      weightCharge,
      distanceCharge,
      expressCharge,
      insuranceCharge,
      taxes,
      discount,
      totalAmount,
      couponCode,
      couponDiscount,
      isInsured,
      insuranceAmount,
      isScheduled,
      scheduledPickupTime,
      paymentMethod,
      estimatedPickupTime,
      estimatedDeliveryTime,
      // New fields for enhanced parcel booking
      declaredValue,
      hasInvoice,
      instructions,
    } = body

    // Validate required fields
    if (!senderId || !senderName || !senderPhone || !recipientName || !recipientPhone || !parcelType || !pickupAddress || !deliveryAddress) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Generate delivery OTP (4 digit code for delivery confirmation)
    const deliveryOtp = Math.floor(1000 + Math.random() * 9000).toString()

    // Insert the order - tracking_number will be auto-generated by database trigger (GMC0001 format)
    const { data, error } = await supabase
      .from('parcel_orders')
      .insert({
        sender_id: senderId,
        sender_name: senderName,
        sender_phone: senderPhone,
        sender_email: senderEmail || null,
        recipient_name: recipientName,
        recipient_phone: recipientPhone,
        recipient_email: recipientEmail || null,
        parcel_type: parcelType,
        parcel_type_name: parcelTypeName || parcelType,
        parcel_weight: parcelWeight || null,
        parcel_description: parcelDescription || null,
        pickup_address: pickupAddress,
        delivery_address: deliveryAddress,
        distance_km: distanceKm || null,
        delivery_type: deliveryType || 'same-day',
        base_price: basePrice || 0,
        weight_charge: weightCharge || 0,
        distance_charge: distanceCharge || 0,
        express_charge: expressCharge || 0,
        insurance_charge: insuranceCharge || 0,
        taxes: taxes || 0,
        discount: discount || 0,
        total_amount: totalAmount || 0,
        coupon_code: couponCode || null,
        coupon_discount: couponDiscount || 0,
        is_insured: isInsured || false,
        insurance_amount: insuranceAmount || 0,
        is_scheduled: isScheduled || false,
        scheduled_pickup_time: scheduledPickupTime || null,
        status: 'pending',
        payment_method: paymentMethod || 'cash',
        payment_status: 'pending',
        delivery_otp: deliveryOtp,
        estimated_pickup_time: estimatedPickupTime || null,
        estimated_delivery_time: estimatedDeliveryTime || null,
        // New fields for enhanced parcel booking
        declared_value: declaredValue || 0,
        has_invoice: hasInvoice || false,
        special_instructions: instructions || null,
      })
      .select()
      .single()

    if (error) {
      console.error('Error creating parcel order:', error)
      return NextResponse.json(
        { error: 'Failed to create order', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      order: data,
      trackingNumber: data.tracking_number, // Auto-generated by database (GMC0001 format)
      message: 'Parcel order created successfully'
    })

  } catch (error) {
    console.error('Error in parcel order API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// GET - Get parcel orders for a user
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const userId = searchParams.get('userId')
    const orderId = searchParams.get('orderId')
    const trackingNumber = searchParams.get('trackingNumber')
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '20')
    const offset = parseInt(searchParams.get('offset') || '0')

    let query = supabase
      .from('parcel_orders')
      .select('*')
      .order('created_at', { ascending: false })

    if (userId) {
      query = query.eq('sender_id', userId)
    }

    if (orderId) {
      query = query.eq('id', orderId)
    }

    if (trackingNumber) {
      query = query.eq('tracking_number', trackingNumber)
    }

    if (status) {
      query = query.eq('status', status)
    }

    query = query.range(offset, offset + limit - 1)

    const { data, error, count } = await query

    if (error) {
      console.error('Error fetching parcel orders:', error)
      return NextResponse.json(
        { error: 'Failed to fetch orders', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      orders: data || [],
      count: count || 0
    })

  } catch (error) {
    console.error('Error in parcel order GET API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// PATCH - Update parcel order status
export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json()
    const { orderId, status, partnerId, partnerName, partnerPhone, partnerPhoto, vehicleNumber, deliveryProofImage, rating, review } = body

    if (!orderId) {
      return NextResponse.json(
        { error: 'Order ID is required' },
        { status: 400 }
      )
    }

    const updateData: Record<string, unknown> = {}
    
    if (status) updateData.status = status
    if (partnerId) updateData.partner_id = partnerId
    if (partnerName) updateData.partner_name = partnerName
    if (partnerPhone) updateData.partner_phone = partnerPhone
    if (partnerPhoto) updateData.partner_photo = partnerPhoto
    if (vehicleNumber) updateData.vehicle_number = vehicleNumber
    if (deliveryProofImage) updateData.delivery_proof_image = deliveryProofImage
    if (rating) updateData.rating = rating
    if (review) updateData.review = review
    
    // Auto-set timestamps based on status
    if (status === 'picked_up') {
      updateData.picked_up_at = new Date().toISOString()
    } else if (status === 'delivered') {
      updateData.delivered_at = new Date().toISOString()
    }

    const { data, error } = await supabase
      .from('parcel_orders')
      .update(updateData)
      .eq('id', orderId)
      .select()
      .single()

    if (error) {
      console.error('Error updating parcel order:', error)
      return NextResponse.json(
        { error: 'Failed to update order', details: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      order: data,
      message: 'Order updated successfully'
    })

  } catch (error) {
    console.error('Error in parcel order PATCH API:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
