-- Backfill canonical allowed_actions for all known access_point_group values.
-- This ensures cards show real permissions (VIEW/UPDATE/ASSIGN/etc), not fallback-only values.

UPDATE public.dashboard_access_points
SET
  allowed_actions = CASE upper(trim(access_point_group))
    WHEN 'RIDER_VIEW' THEN '["VIEW"]'::jsonb
    WHEN 'RIDER_ACTIONS_FOOD' THEN '["UPDATE","CANCEL","BLOCK","UNBLOCK"]'::jsonb
    WHEN 'RIDER_ACTIONS_PARCEL' THEN '["UPDATE","CANCEL","BLOCK","UNBLOCK"]'::jsonb
    WHEN 'RIDER_ACTIONS_PERSON_RIDE' THEN '["UPDATE","CANCEL","BLOCK","UNBLOCK"]'::jsonb
    WHEN 'RIDER_WALLET_CREDITS' THEN '["CREATE","VIEW","APPROVE","REJECT"]'::jsonb

    WHEN 'MERCHANT_VIEW' THEN '["VIEW"]'::jsonb
    WHEN 'MERCHANT_ONBOARDING' THEN '["UPDATE","APPROVE","REJECT"]'::jsonb
    WHEN 'MERCHANT_OPERATIONS' THEN '["UPDATE"]'::jsonb
    WHEN 'MERCHANT_STORE_MANAGEMENT' THEN '["CREATE","UPDATE","DELETE"]'::jsonb
    WHEN 'MERCHANT_WALLET' THEN '["UPDATE"]'::jsonb
    WHEN 'MERCHANT_ADMIN_MERCHANT_ACCESS' THEN '["ADMIN_MERCHANT_PANEL"]'::jsonb

    WHEN 'CUSTOMER_VIEW' THEN '["VIEW"]'::jsonb
    WHEN 'CUSTOMER_ACTIONS_FOOD' THEN '["BLOCK","UNBLOCK","UPDATE"]'::jsonb
    WHEN 'CUSTOMER_ACTIONS_PARCEL' THEN '["BLOCK","UNBLOCK","UPDATE"]'::jsonb
    WHEN 'CUSTOMER_ACTIONS_PERSON_RIDE' THEN '["BLOCK","UNBLOCK","UPDATE"]'::jsonb

    WHEN 'ORDER_VIEW' THEN '["VIEW"]'::jsonb
    WHEN 'ORDER_ASSIGN' THEN '["ASSIGN","UPDATE"]'::jsonb
    WHEN 'ORDER_CANCEL' THEN '["CANCEL","UPDATE"]'::jsonb
    WHEN 'ORDER_REFUND' THEN '["REFUND","UPDATE"]'::jsonb

    WHEN 'TICKET_VIEW_FOOD' THEN '["VIEW"]'::jsonb
    WHEN 'TICKET_VIEW_PARCEL' THEN '["VIEW"]'::jsonb
    WHEN 'TICKET_VIEW_PERSON_RIDE' THEN '["VIEW"]'::jsonb
    WHEN 'TICKET_ACTIONS_FOOD' THEN '["ASSIGN","UPDATE","APPROVE","REJECT"]'::jsonb
    WHEN 'TICKET_ACTIONS_PARCEL' THEN '["ASSIGN","UPDATE","APPROVE","REJECT"]'::jsonb
    WHEN 'TICKET_ACTIONS_PERSON_RIDE' THEN '["ASSIGN","UPDATE","APPROVE","REJECT"]'::jsonb
    WHEN 'TICKET_AGENT_STATUS_TOGGLE' THEN '["UPDATE"]'::jsonb
    WHEN 'TICKET_QUEUE_SUPERVISOR' THEN '["VIEW"]'::jsonb
    WHEN 'TICKET_QUEUE_MANAGER' THEN '["VIEW"]'::jsonb

    WHEN 'OFFER_RIDER' THEN '["CREATE","UPDATE","DELETE"]'::jsonb
    WHEN 'OFFER_CUSTOMER' THEN '["CREATE","UPDATE","DELETE"]'::jsonb
    WHEN 'OFFER_MERCHANT' THEN '["CREATE","UPDATE","DELETE"]'::jsonb

    WHEN 'AREA_MANAGER_MERCHANT' THEN '["CREATE","UPDATE","APPROVE","VIEW"]'::jsonb
    WHEN 'AREA_MANAGER_RIDER' THEN '["CREATE","UPDATE","APPROVE","VIEW"]'::jsonb

    WHEN 'PAYMENT_MANAGEMENT' THEN '["VIEW","UPDATE","APPROVE","REJECT","CANCEL"]'::jsonb
    ELSE allowed_actions
  END,
  updated_at = NOW()
WHERE upper(trim(access_point_group)) IN (
  'RIDER_VIEW',
  'RIDER_ACTIONS_FOOD',
  'RIDER_ACTIONS_PARCEL',
  'RIDER_ACTIONS_PERSON_RIDE',
  'RIDER_WALLET_CREDITS',
  'MERCHANT_VIEW',
  'MERCHANT_ONBOARDING',
  'MERCHANT_OPERATIONS',
  'MERCHANT_STORE_MANAGEMENT',
  'MERCHANT_WALLET',
  'MERCHANT_ADMIN_MERCHANT_ACCESS',
  'CUSTOMER_VIEW',
  'CUSTOMER_ACTIONS_FOOD',
  'CUSTOMER_ACTIONS_PARCEL',
  'CUSTOMER_ACTIONS_PERSON_RIDE',
  'ORDER_VIEW',
  'ORDER_ASSIGN',
  'ORDER_CANCEL',
  'ORDER_REFUND',
  'TICKET_VIEW_FOOD',
  'TICKET_VIEW_PARCEL',
  'TICKET_VIEW_PERSON_RIDE',
  'TICKET_ACTIONS_FOOD',
  'TICKET_ACTIONS_PARCEL',
  'TICKET_ACTIONS_PERSON_RIDE',
  'TICKET_AGENT_STATUS_TOGGLE',
  'TICKET_QUEUE_SUPERVISOR',
  'TICKET_QUEUE_MANAGER',
  'OFFER_RIDER',
  'OFFER_CUSTOMER',
  'OFFER_MERCHANT',
  'AREA_MANAGER_MERCHANT',
  'AREA_MANAGER_RIDER',
  'PAYMENT_MANAGEMENT'
);
