-- Versioned licence history: never delete prior uploads; chain via previous_licence_id / replaced_by.

CREATE TABLE IF NOT EXISTS public.merchant_licence_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES public.merchant_stores (id) ON DELETE CASCADE,
  parent_id bigint NULL,
  licence_type text NOT NULL,
  licence_number text NULL,
  file_url text NOT NULL,
  file_name text NULL,
  back_file_url text NULL,
  issued_at date NULL,
  expires_at date NULL,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  verification_status text NOT NULL DEFAULT 'pending'
    CHECK (verification_status IN ('pending', 'verified', 'rejected', 'expired')),
  is_active boolean NOT NULL DEFAULT false,
  is_expired boolean NOT NULL DEFAULT false,
  replaced_by bigint NULL REFERENCES public.merchant_licence_history (id) ON DELETE SET NULL,
  previous_licence_id bigint NULL REFERENCES public.merchant_licence_history (id) ON DELETE SET NULL,
  document_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS merchant_licence_history_store_type_idx
  ON public.merchant_licence_history (store_id, licence_type);

CREATE INDEX IF NOT EXISTS merchant_licence_history_store_active_idx
  ON public.merchant_licence_history (store_id, licence_type)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS merchant_licence_history_uploaded_at_idx
  ON public.merchant_licence_history (store_id, uploaded_at DESC);

COMMENT ON TABLE public.merchant_licence_history IS
  'Immutable licence upload versions per store. Current row mirrored on merchant_store_documents; history never deleted.';

-- Backfill one history row per document type that already has a file on merchant_store_documents.
DO $$
DECLARE
  r record;
  j jsonb;
  prefixes text[] := ARRAY[
    'pan', 'gst', 'aadhaar', 'fssai', 'drug_license', 'shop_establishment',
    'trade_license', 'udyam', 'pharmacist_certificate', 'pharmacy_council_registration', 'other'
  ];
  p text;
  v_url text;
  v_num text;
  v_exp date;
  v_ver boolean;
  v_expired boolean;
  v_meta jsonb;
  v_back text;
  v_status text;
BEGIN
  IF to_regclass('public.merchant_store_documents') IS NULL THEN
    RETURN;
  END IF;

  FOR r IN SELECT * FROM public.merchant_store_documents LOOP
    j := to_jsonb(r);
    FOREACH p IN ARRAY prefixes LOOP
      v_url := NULLIF(trim(j ->> (p || '_document_url')), '');
      IF v_url IS NULL THEN
        CONTINUE;
      END IF;

      IF EXISTS (
        SELECT 1 FROM public.merchant_licence_history h
        WHERE h.store_id = r.store_id AND h.licence_type = p AND h.file_url = v_url
      ) THEN
        CONTINUE;
      END IF;

      v_num := j ->> (p || '_document_number');
      v_exp := (j ->> (p || '_expiry_date'))::date;
      v_ver := (j ->> (p || '_is_verified'))::boolean;
      v_expired := COALESCE((j ->> (p || '_is_expired'))::boolean, FALSE);
      v_meta := COALESCE(j -> (p || '_document_metadata'), '{}'::jsonb);
      v_back := NULLIF(trim(v_meta ->> 'back_url'), '');

      v_status := CASE
        WHEN v_expired IS TRUE THEN 'expired'
        WHEN v_ver IS TRUE THEN 'verified'
        ELSE 'pending'
      END;

      INSERT INTO public.merchant_licence_history (
        store_id,
        licence_type,
        licence_number,
        file_url,
        back_file_url,
        expires_at,
        uploaded_at,
        verification_status,
        is_active,
        is_expired,
        document_metadata
      ) VALUES (
        r.store_id,
        p,
        NULLIF(trim(v_num), ''),
        v_url,
        v_back,
        v_exp,
        COALESCE((r.updated_at)::timestamptz, (r.created_at)::timestamptz, now()),
        v_status,
        TRUE,
        v_expired,
        v_meta
      );
    END LOOP;
  END LOOP;
END $$;
