import { StyleSheet } from "react-native";
import { GatiMitraMerchant, CARD_RADIUS } from "@/constants/theme";

export const merchantOrderCardLayoutStyles = StyleSheet.create({
  wrap: {
    borderRadius: CARD_RADIUS,
    overflow: "hidden",
    ...GatiMitraMerchant.shadowSm,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    overflow: "hidden",
  },
  cardUnderBanner: {
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 6,
  },
  headerRowAfterBadge: {
    paddingTop: 6,
  },
  headerLeft: { flex: 1, minWidth: 0, gap: 4 },
  storeName: { fontSize: 12, fontWeight: "500", color: "#666666" },
  customerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 14,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#EEEEEE",
  },
  customerLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1A1A",
    minWidth: 0,
  },
  placedAt: { fontSize: 12, fontWeight: "500", color: "#666666" },
  section: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#EEEEEE",
  },
  sectionHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  billSectionHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minHeight: 48,
  },
  sectionTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  sectionMeta: { fontSize: 12, fontWeight: "500", color: "#666666" },
  itemsBox: { paddingHorizontal: 14, paddingBottom: 10, gap: 6 },
  moreItems: {
    fontSize: 12,
    fontWeight: "700",
    color: GatiMitraMerchant.textSecondary,
  },
  instructionsMargin: {
    marginHorizontal: 14,
    marginBottom: 8,
  },
  billAmount: { fontSize: 14, fontWeight: "700", color: "#1A1A1A" },
  billBreakdown: { paddingHorizontal: 14, paddingBottom: 10, gap: 8 },
  billSummaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  billSummaryLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: "500",
    color: GatiMitraMerchant.textSecondary,
    lineHeight: 18,
  },
  billSummaryLabelDotted: {
    textDecorationLine: "underline",
    textDecorationStyle: "dotted",
    textDecorationColor: GatiMitraMerchant.textTertiary,
  },
  billSummaryAmount: {
    fontSize: 13,
    fontWeight: "600",
    color: GatiMitraMerchant.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  billSummaryDiscount: {
    color: GatiMitraMerchant.primaryDark,
  },
  statusBadgeRow: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  statusBadgeLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  terminalFooterStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingTop: 4,
  },
  terminalFooterText: {
    fontSize: 13,
    fontWeight: "600",
  },
  terminalReasonText: {
    fontSize: 13,
    lineHeight: 19,
    color: GatiMitraMerchant.textSecondary,
  },
  terminalReasonPrefix: {
    fontWeight: "600",
  },
  footer: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 10,
  },
  riderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  riderAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#E8E8E8",
    alignItems: "center",
    justifyContent: "center",
  },
  riderText: { flex: 1, fontSize: 13, fontWeight: "500", color: "#1A1A1A" },
  pressed: { opacity: 0.9 },
});
