import { StyleSheet } from "react-native";
import { GatiMitraMerchant, CARD_RADIUS, H_PADDING } from "@/constants/theme";

export const OFFERS_UI = {
  pageBg: GatiMitraMerchant.background,
  cardBg: GatiMitraMerchant.cardBg,
  cardBorder: GatiMitraMerchant.border,
  accent: GatiMitraMerchant.primary,
  accentSoft: "#E8F8F1",
  navy: GatiMitraMerchant.navy,
  text: GatiMitraMerchant.textPrimary,
  textMuted: GatiMitraMerchant.textSecondary,
  textFaint: GatiMitraMerchant.textTertiary,
  pillActiveBg: GatiMitraMerchant.primary,
  pillActiveText: "#fff",
  pillInactiveBg: GatiMitraMerchant.surfaceSubtle,
  pillInactiveText: GatiMitraMerchant.textPrimary,
  tabActive: GatiMitraMerchant.primary,
  tabInactive: GatiMitraMerchant.textSecondary,
  warningBanner: "#FFF7ED",
  warningBorder: "#FDBA74",
  warningText: "#9A3412",
  liveGreen: GatiMitraMerchant.success,
  metricDivider: GatiMitraMerchant.border,
};

export const offersSharedStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: OFFERS_UI.pageBg },
  scrollContent: { paddingBottom: 48 },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: OFFERS_UI.text,
    marginBottom: 12,
    paddingHorizontal: H_PADDING,
  },
  card: {
    marginHorizontal: H_PADDING,
    backgroundColor: OFFERS_UI.cardBg,
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: OFFERS_UI.cardBorder,
    overflow: "hidden",
    ...GatiMitraMerchant.shadowSm,
  },
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: OFFERS_UI.cardBorder,
    paddingHorizontal: H_PADDING,
    backgroundColor: OFFERS_UI.pageBg,
  },
  tabBtn: {
    paddingVertical: 14,
    marginRight: 28,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tabBtnActive: { borderBottomColor: OFFERS_UI.tabActive },
  tabText: { fontSize: 15, fontWeight: "600", color: OFFERS_UI.tabInactive },
  tabTextActive: { color: OFFERS_UI.tabActive, fontWeight: "700" },
  tabBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: OFFERS_UI.pillInactiveBg,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  tabBadgeActive: { backgroundColor: OFFERS_UI.accentSoft },
  tabBadgeText: { fontSize: 11, fontWeight: "700", color: OFFERS_UI.textMuted },
  tabBadgeTextActive: { color: OFFERS_UI.accent },
});
