/** Short keys matching GET /v1/app-assets/customer → assets map. */
export const CX = {
  auth: {
    logo: "auth.logo",
    logoWithName: "auth.logo_with_name",
  },
  brand: {
    appIcon: "brand.app_icon",
  },
  home: {
    brandBanner: "home.brand_banner",
    serviceFood: "home.service_food",
    serviceRide: "home.service_ride",
    serviceParcel: "home.service_parcel",
    serviceEcommerce: "home.service_ecommerce",
    serviceVoucher: "home.service_voucher",
    serviceLocation: "home.service_location",
    promoOffer: "home.promo_offer",
    promoOffer2: "home.promo_offer_2",
    promoRideOffer1: "home.promo_ride_offer_1",
    promoRideOffer2: "home.promo_ride_offer_2",
  },
  ride: {
    banner: "ride.banner",
    bottomBanner: "ride.bottom_banner",
    bike: "ride.bike",
    auto: "ride.auto",
    cab: "ride.cab",
    cabPremium: "ride.cab_premium",
    travel: "ride.travel",
    rideCard: "ride.ride_card",
    waitingHero: "ride.waiting_hero",
    mapBike: "ride.map_bike",
    mapAuto: "ride.map_auto",
    mapCab: "ride.map_cab",
    mapTravel: "ride.map_travel",
  },
  search: {
    biryani: "search.biryani",
    chicken: "search.chicken",
    pizza: "search.pizza",
    northIndian: "search.north_indian",
    paneer: "search.paneer",
    chinese: "search.chinese",
    cake: "search.cake",
    vegMeal: "search.veg_meal",
    sweets: "search.sweets",
    thali: "search.thali",
    burger: "search.burger",
    rolls: "search.rolls",
    noodles: "search.noodles",
    dosa: "search.dosa",
    momos: "search.momos",
    friedRice: "search.fried_rice",
    chilliChicken: "search.chilli_chicken",
    pavBhaji: "search.pav_bhaji",
    default: "search.default",
  },
  orders: {
    postDeliveryHero: "orders.post_delivery_hero",
    support: "orders.support",
    supportHero: "orders.support_hero",
    toastLogo: "orders.toast_logo",
  },
  checkout: {
    rxTip: "checkout.rx_tip",
    fed: "checkout.fed",
  },
  common: {
    defaultImage: "common.default_image",
    emptySearch: "common.empty_search",
  },
  store: {
    footerPromo: "store.footer_promo",
    longDistanceSheet: "store.long_distance_sheet",
  },
  shop: {
    product: (n: number) => `shop.product_${n}` as const,
  },
} as const;

/** Map search slug → asset key */
export const SEARCH_SLUG_TO_ASSET_KEY: Record<string, string> = {
  biryani: CX.search.biryani,
  chicken: CX.search.chicken,
  pizza: CX.search.pizza,
  "north-indian": CX.search.northIndian,
  paneer: CX.search.paneer,
  chinese: CX.search.chinese,
  cake: CX.search.cake,
  "veg-meal": CX.search.vegMeal,
  sweets: CX.search.sweets,
  thali: CX.search.thali,
  burger: CX.search.burger,
  rolls: CX.search.rolls,
  noodles: CX.search.noodles,
  dosa: CX.search.dosa,
  momos: CX.search.momos,
  "fried-rice": CX.search.friedRice,
  "chilli-chicken": CX.search.chilliChicken,
  "pav-bhaji": CX.search.pavBhaji,
  default: CX.search.default,
};
